### ISSUE TITLE
Codebuild fails since it is not finding the builspec.yml file

### ISSUE THREAD

**Issue by zensim** [aws-samples/mlops-e2e#68]
below is the error msg.  Please advise. Thanks

[Container] 2024/06/05 02:04:07.161900 Running on CodeBuild On-demand
--
2 | [Container] 2024/06/05 02:04:07.161914 Waiting for agent ping
3 | [Container] 2024/06/05 02:04:07.363563 Waiting for DOWNLOAD_SOURCE
4 | [Container] 2024/06/05 02:04:08.786311 Phase is DOWNLOAD_SOURCE
5 | [Container] 2024/06/05 02:04:08.787251 CODEBUILD_SRC_DIR=/codebuild/output/src2740/src/s3/00
6 | [Container] 2024/06/05 02:04:08.787420 CODEBUILD_SRC_DIR_SourceDataOutput=/codebuild/output/src2740/src/s3/01
7 | [Container] 2024/06/05 02:04:08.791498 Phase complete: DOWNLOAD_SOURCE State: FAILED
8 | [Container] 2024/06/05 02:04:08.791520 Phase context status code: YAML_FILE_ERROR Message: stat /codebuild/output/src2740/src/s3/00/buildspecs/build.yml: no such file or directory

**Comment by jessieweiyi** [comment]
Hi @zensim  The error message shows `Phase complete: DOWNLOAD_SOURCE State: FAILED`. Did you push the code to the code repository created by the stack? The code push should trigger a code build.
