### ISSUE TITLE
Quick question 

### ISSUE THREAD

**Issue by MABatin** [aws-samples/mlops-e2e#78]
Hi great end-to-end MLOps example. I was wondering if it's possible for me setup a project like this with two different source repositories, one for the Python ML code and another for the Typescript CDK code. Would that work?
Would highly appreciate if you could answer.
Thanks in advance 😃

**Comment by jessieweiyi** [comment]
Hi @MABatin 

Thanks for reaching out and thanks for your contributions on upgrading the project code. 

Yes, you can use 2 separate repositories to manage Typescript CDK/API Backend/UI code and python code separately. 

If we use this repository as examples, you can split all the typescript projects consumers/infrastructure/model_deploy into one monorepo, and the python project ml_pipeline/src+test into the other monorepo containing 2 python projects. 

To connect them together:

1. In the infrastructure project, you will need to add a new sourceAction for the additional source repo in `./infrastructure/lib/codePipelineConstruct.ts` file. The 2 source repo will be downloaded as 2 separate folders. And [here](https://docs.aws.amazon.com/codebuild/latest/userguide/sample-codepipeline.html#sample-pipeline-multi-input-output) is an example on how you can find the folders.

2. You need to adjust the build/deploy script under scripts folder.

**Comment by jessieweiyi** [comment]
Close this issue for now. Please feel free to reopen if you have further questions.
